apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineParams
metadata:
  name: pipelineparams-sample
  namespace: default
spec:
  clusters:
    - name: 'testCluster'
      type: 'gke'
      endpoint: 'https://test.gke.corp.com'
